/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FeedbackForm: typeof import('./src/components/feedback/FeedbackForm.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Image: typeof import('primevue/image')['default']
    InformationBox: typeof import('./src/components/shared/InformationBox.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MapComponent: typeof import('./src/components/MapComponent.vue')['default']
    MapSearchBarComponent: typeof import('./src/components/MapSearchBarComponent.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PlaceholderComponent: typeof import('./src/components/shared/PlaceholderComponent.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouteInformationComponent: typeof import('./src/components/RouteInformationComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RoutesListComponent: typeof import('./src/components/RoutesListComponent.vue')['default']
    SchedulesComponent: typeof import('./src/components/schedules/SchedulesComponent.vue')['default']
    SearchForm: typeof import('./src/components/shared/SearchForm.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TransportationDropdown: typeof import('./src/components/shared/TransportationDropdown.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
