# Generated by Django 5.1.2 on 2024-10-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('from_location', models.CharField(max_length=255)),
                ('from_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('from_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('to_location', models.CharField(max_length=255)),
                ('to_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('to_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('travel_class', models.CharField(max_length=50)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travel_days', models.CharField(max_length=50)),
            ],
        ),
    ]
