# Generated by Django 5.1.2 on 2024-10-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='arrival_time',
            field=models.TimeField(blank=True, help_text='Format: HH:MM AM/PM', null=True),
        ),
    ]
