# Generated by Django 5.1.2 on 2024-10-23 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_ferryschedule_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferryschedule',
            name='arrival_time',
        ),
    ]
