# Generated by Django 5.1.2 on 2024-11-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_remove_ferryschedule_arrival_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferryschedule',
            name='passenger_type',
        ),
        migrations.AddField(
            model_name='ferryschedule',
            name='arrival_time',
            field=models.TimeField(blank=True, help_text='Format: HH:MM', null=True),
        ),
        migrations.AlterField(
            model_name='ferryschedule',
            name='departure_time',
            field=models.TimeField(blank=True, help_text='Format: HH:MM', null=True),
        ),
    ]
