# Generated by Django 5.1.2 on 2024-11-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_alter_ferryschedule_from_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferryschedule',
            name='accommodation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ferryschedule',
            name='day_of_departure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ferryschedule',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ferryschedule',
            name='vessel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
