# Generated by Django 5.1.2 on 2024-11-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='distance',
            new_name='from_lat',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='end_point',
            new_name='from_location',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='start_point',
            new_name='to_location',
        ),
        migrations.AddField(
            model_name='route',
            name='from_lng',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='to_lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='to_lng',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
