# Generated by Django 5.1.2 on 2024-11-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_rename_distance_route_from_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='from_lat',
        ),
        migrations.RemoveField(
            model_name='route',
            name='from_lng',
        ),
        migrations.RemoveField(
            model_name='route',
            name='to_lat',
        ),
        migrations.RemoveField(
            model_name='route',
            name='to_lng',
        ),
        migrations.AlterField(
            model_name='route',
            name='from_location',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='to_location',
            field=models.JSONField(),
        ),
    ]
