# Generated by Django 5.1.2 on 2024-11-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_remove_route_from_lat_remove_route_from_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='from_coords',
            field=models.JSONField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='to_coords',
            field=models.JSONField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='from_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='to_location',
            field=models.CharField(max_length=100),
        ),
    ]
